A2 team sprint 1 szenzorok
SzFMV2023-Osz/AutomatedCar-A pull request #105
Opened 2023-12-01 12:07 UTC by Lexykee

merging the latest changes into the develop for other teams to reach the packets

2023-12-01 12:16 UTC, gegenyattila commented on src/AutomatedCar/SystemComponents/InputHandling/KeyboardHandler.cs
> +            this.shiftingDirection = SequentialShiftingDirections.Nothing;
Miért van itt 2 ugyanolyan sor?

2023-12-01 12:18 UTC, gegenyattila commented on src/AutomatedCar/SystemComponents/LaneKeepingAssistant/45degreeCheck.cs
> +            else if (angleAsDegree > 45 || angleAsDegree < -45 || angleAsDegree < 30)
angleAsDegree < 30 ellenőrzés miatt nem működik jól az LKA ki-bekapcsolás!

2023-12-01 12:21 UTC, gegenyattila commented on src/AutomatedCar/SystemComponents/MovementCalculator.cs
> +
Ezt nem tudom ki és miért kommentelte ki. Nincs ezekre a sorokra szükség?

2023-12-01 19:13 UTC, skincso requested changes

2023-12-01 19:13 UTC, skincso commented on src/AutomatedCar/SystemComponents/LaneKeepingAssistant/45degreeCheck.cs
> +    public class _45degreeCheck : SystemComponent, IWheel
Why does it inherit from SystemComponent and IWheel?

2023-12-01 19:13 UTC, skincso commented on src/AutomatedCar/SystemComponents/Packets/LKAHandlerPacket.cs
Please move this implementation to LKAInputPacket.cs

2023-12-01 19:13 UTC, skincso commented on src/AutomatedCar/SystemComponents/Packets/RelevantObjectsHandlerPacket.cs
Please rename it to RadarPacket or something similar, because this way is not obvious that it's from the radar sensor.

2023-12-01 19:13 UTC, skincso commented on src/AutomatedCar/SystemComponents/Sensor.cs
> +        public RelevantObjectsHandlerPacket RelevantObjectsPacket { get; set; }
Why does Sensor class need to access this packet? (E.g. camera doesn't use it)

2023-12-01 19:13 UTC, skincso commented on src/AutomatedCar/SystemComponents/VirtualFunctionBus.cs
> +        public IReadOnlyLKAHandlerPacket LKAHandlerPacket { get; set; }
This isn't needed here, LKAInputPacket is already added to VFB

2023-12-04 19:22 UTC, VELOC1Ty01 commented
> For the lack of review hereby I close this pr

Sorry but WHAT?
There are at least 10 changes requested and questions asked. 
None have been answered or resolved so far. 
This pr is literally blocking every sprint 2 project.

2023-12-04 19:38 UTC, Lexykee commented
We discussed with Team-1 and 2 that we will close this pr and make a new one because lot of the team-2 members could not make a review till team one made changes to develop. We have to change so many things we decided to make new  pr with another branch. This is why we closed the pr.

2023-12-05 10:08 UTC, OroszDan commented on src/AutomatedCar/SystemComponents/MovementCalculator.cs
> +
Szerintem ez nem a mi csapatunk hatásköre ha jól tudom

2023-12-06 18:23 UTC, Bobafeti1998 approved these changes
Geroniimooo

2023-12-06 18:26 UTC, Bobafeti1998 approved these changes

2023-12-06 18:27 UTC, merged