Feature/id 88 powertrain input priority handler
SzFMV2023-Osz/AutomatedCar-A pull request #97
Opened 2023-11-21 14:13 UTC by VELOC1Ty01

2023-11-21 17:42 UTC, skincso requested changes
Please update your branch with the develop branch

2023-11-21 17:42 UTC, skincso commented on src/AutomatedCar/SystemComponents/Packets/InputPackets/LCCInputPacket.cs
ACC (Adaptive Cruise Control)

2023-11-22 17:29 UTC, VELOC1Ty01 commented on src/AutomatedCar/SystemComponents/Packets/InputPackets/LCCInputPacket.cs
Corrected

2023-11-22 17:37 UTC, DanShepherd27 approved these changes
Együtt néztük át Teams hívásban, részemről oké.
(Az InputDevicePacket.cs-ben a négy getter-setterben hiányzik a "this.", akinek van kedve, beírhatja)

2023-11-22 18:11 UTC, skincso approved these changes

2023-11-22 18:11 UTC, merged